modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "economycraft"
version = "${version}"
displayName = "EconomyCraft"
authors = "ReaZip"
logoFile = "assets/economycraft/logo.png"
description = '''
Simple server-side economy and shop mod.
'''

# ---- Minecraft:
[[dependencies.economycraft]]
modId = "minecraft"
type = "required"
versionRange = "[${mcLo},${mcHi})"
ordering = "NONE"
side = "BOTH"

# ---- NeoForge:
[[dependencies.economycraft]]
modId = "neoforge"
type = "required"
versionRange = "[${nfLo},${nfHi})"
ordering = "NONE"
side = "BOTH"

# ---- Architectury:
[[dependencies.economycraft]]
modId = "architectury"
type = "required"
versionRange = "[${archVer},)"
ordering = "NONE"
side = "BOTH"

# ---- Placeholder API NeoForge (optional, for mod-to-mod placeholder integration):
[[dependencies.economycraft]]
modId = "placeholder-api-neoforge"
type = "optional"
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"
